### ISSUE TITLE
Error when running table recognition evaluation

### ISSUE THREAD

**Issue by zhxgj** [tamirhassan/dataset-tools#1]
Hi, I used the following command to use the jar to evaluate my table recognitions. 
`java -jar dataset-tools-20180206.jar -reg eu-001`

But I got the error message below:
`Using     GTFile: eu-001-reg.xml
Using resultFile: eu-001-reg-result.xml
Using    PDFFile: eu-001.pdf
startPage: 1
endPage: 2147483647
Current page no: 1
Exception in thread "main" java.lang.NoClassDefFoundError: javax/media/jai/PlanarImage
	at at.ac.tuwien.dbai.pdfwrap.model.document.GenericSegment.tagName(GenericSegment.java:425)
	at at.ac.tuwien.dbai.pdfwrap.model.document.GenericSegment.toString(GenericSegment.java:215)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at at.ac.tuwien.dbai.pdfwrap.pdfread.PDFObjectExtractor.processPages(PDFObjectExtractor.java:1464)
	at at.ac.tuwien.dbai.pdfwrap.pdfread.PDFObjectExtractor.findObjects(PDFObjectExtractor.java:1413)
	at at.ac.tuwien.dbai.pdfwrap.ProcessFile.processPDF(ProcessFile.java:188)
	at at.ac.tuwien.dbai.pdfwrap.MeasureRecognitionPerformance.main(MeasureRecognitionPerformance.java:291)
Caused by: java.lang.ClassNotFoundException: javax.media.jai.PlanarImage
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 8 more
`

My result file is attached below.
[eu-001-reg-result.xml.zip](https://github.com/tamirhassan/dataset-tools/files/1930751/eu-001-reg-result.xml.zip)

Could you please help me with this error? Thank you very much.

**Comment by CAROLZXYZXY** [comment]
I have the same problem. Have you solved this?

**Comment by CAROLZXYZXY** [comment]
[dataset-tools.jar.zip](https://github.com/tamirhassan/dataset-tools/files/3245409/dataset-tools.jar.zip)
I have added the dependencies. I think this jar file should be correct now.

**Comment by AHoou** [comment]
@zhxgj  @tamirhassan  Hi,have you slolved this problem? I am facing the problem either, and do not know how to slove it.

**Comment by zhxgj** [comment]
@GZDXLQH I did not attempt to solve it because I am not familiar with java...

**Comment by GZDXLQH** [comment]
> @GZDXLQH I did not attempt to solve it because I am not familiar with java...
ok，thanks for your replay

**Comment by AHoou** [comment]
> @GZDXLQH I did not attempt to solve it because I am not familiar with java...

@zhxgj  OK, thanks for your replay.

**Comment by tamirhassan** [comment]
Hi, there seems to be some problem with dependencies. Sorry about this. I will do a new build next week and update the libraries to the newest ones. In the meantime, you need to add com.springsource.javax.media.jai.core-1.1.3.jar, pdfbox-app-1.8.1.jar (not pdfbox-1.8.1.jar) and commons-collections-3.1.jar to the classpath and it should work.

**Comment by tamirhassan** [comment]
I have now pushed these extra JARs to the /lib directory. I will look at the code next week and see if I can remove these dependencies, but this should get you up and running for the time being.

**Comment by AHoou** [comment]
> I have now pushed these extra JARs to the /lib directory. I will look at the code next week and see if I can remove these dependencies, but this should get you up and running for the time being.

Thanks！I will try it according to your steps！

**Comment by chuong-phung** [comment]
Hi @tamirhassan  @GZDXLQH ,
I got the same problem. How can I fix it?
I have added  com.springsource.javax.media.jai.core-1.1.3.jar, pdfbox-app-1.8.1.jar (not pdfbox-1.8.1.jar) and commons-collections-3.1.jar to the .classpath file and running with the following command 
`java -jar -classpath .classpath  dataset-tools-20180206.jar -reg ../icdar2013-competition-dataset-with-gt/competition-dataset-eu/eu-001 
`
I get the following error: Error: Could not find or load main class dataset-tools-20180206.jar

**Comment by AHoou** [comment]
@chuong-phung Hi， I am sorry to tell you I can't help you. I am not good at Java. So far, I don’t  have time to re-evaluate the experiment according to tamirhassan's solution. (In fact, before tamirhassan gives me the solution, I have used  the  ICDAR 2019cTDaR tools to evaluate my recognition result of my table).

**Comment by chuong-phung** [comment]
Hi @GZDXLQH ,
Thanks for your replay

**Comment by Dod-o** [comment]
@tamirhassan  hi, I still meet this error. has this problem been solved?

**Comment by rudra0713** [comment]
@tamirhassan Hi, I am also facing a similar error. Have the jar files been updated?
